### PR TITLE
CloudTools

### PR DESCRIPTION
**Pull request by dwheelock**
Functions that perform SSH commands from ECL to do common Landing Zone tasks, such as decompressing files, pulling files from the Internet, and rudimentary file shape analysis.
Still a work in progress.
Some notes at the end regarding code-in-progress, as well as a small set of examples.

### CODE REVIEW

**Comment by richardkchapman** [comment]
@jprichard Any prospect of this moving forward or should I close it?

**Comment by jprichard** [comment]
@richardkchapman what is outstanding still, just the staging to the hthor?

**Comment by richardkchapman** [comment]
Well it's been a while (!) but I think my comment "My main remaining concern is the general utility of this module given it requires hthor and the landing zone (and esp) to be on the same machine." still holds.

**Comment by jprichard** [comment]
@dwheelock I think we need to take a look and see if we can rejig to decouple it from needing the three components all on the same box.

**Comment by richardkchapman** [comment]
Closing as timed out

**Pull request closed without merging**
