### PR TITLE
HPCC-13747 Add some sort algorithm tests to the performance suite

### PR DESCRIPTION
**Pull request by ghalliday**
Signed-off-by: Gavin Halliday <gavin.halliday@lexisnexis.com>

### CODE REVIEW

**Comment by ghalliday** [comment]
@richardkchapman please review/merge

**Comment by richardkchapman** [comment]
Should the bundle version change?

**Comment by richardkchapman** [comment]
@ghalliday ?

**Comment by ghalliday** [comment]
@richardkchapman updated

**Pull request merged**
