### PR TITLE
File Management bundle

### PR DESCRIPTION
**Pull request by johnholt**
A bundle to manage a group of files so that they are all promoted together or none of the files are promotes.  

Signed-off-by: johnholt <john.d.holt@lexisnexisrisk.com>

### CODE REVIEW

**Comment by dcamper** [comment]
@johnholt Should there be more changes in this PR?  I see only a comment change.

**Comment by johnholt** [comment]
Maybe, but I did not think so.  I am thinking that the point of a self supported bundle pull request is just to change this particular file with a link to the bundle repository for the bundle.  In this case, https://github.com/johnholt/File_Management 

I could easily have the incorrect idea.  We used to just have all of the self supported bundles in this repository, but we moved them out so that the bundle tool could install them.

Let me know if I should be doing this differently.

**Comment by johnholt** [comment]
@richardkchapman  What is the process for adding unsupported bundles to the list?

**Comment by richardkchapman** [comment]
@johnholt I think this approach is correct

**Pull request merged**
